### ISSUE TITLE
Use Junit5 version of @Rule and TemporaryFolder

### ISSUE THREAD

**Issue by huehnerlady** [europace/docker-publish-gradle-plugin#15]
Achtung: `TemporaryFolder` ist Gradle internal und sollte eher direkt von `org.junit` importiert werden. Gleiches gilt natürlich für `Rule`.

_Originally posted by @gesellix in https://github.com/europace/spring-boot-docker-publish-gradle-plugin/pull/9#discussion_r616204294_

**Comment by gesellix** [comment]
Es gibt mittlerweile auch eine `@TestDir` annotation in JUnit 4.
