### ISSUE TITLE
Fix update-gradle-wrapper action

### ISSUE THREAD

**Issue by huehnerlady** [europace/docker-publish-gradle-plugin#47]
Die Gradle Wrapper action schlägt fehl (Beispiel siehe [hier](https://github.com/europace/docker-publish-gradle-plugin/actions/runs/1178180542)

Wir brauchen hier ein Token um einen Pullrequest zu erstellen.

**Comment by huehnerlady** [comment]
@gesellix wenn du mal wieder aufräumen willst ;)

**Comment by huehnerlady** [comment]
@gesellix könntest du dir das vielleicht mal anschauen?

**Comment by huehnerlady** [comment]
ggf. müssen wir das Token für alle repos freigeben?
![image](https://user-images.githubusercontent.com/12533979/133228500-53cd880a-6fe3-49b7-9a88-dd531ed1c799.png)

Ist das ok? Ich mein es kann sich ja niemand ziehen, oder?

**Comment by huehnerlady** [comment]
ich musste @PkuBuildGitHub zum repo hinzufügen 🙄

**Comment by gesellix** [comment]
danke @huehnerlady!
